title: 'Rafael Cifuentes '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.75
  brandStrength: 0.6875
  rhythmicContrast: 0
  brandColors:
    - '#ffffff'
    - '#1c1c1c'
    - '#9a9a9a'
    - '#777777'
    - '#dbdbdb'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: RCGLIV
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.35997
layout_spectrum: 0.1989247
