name: RCGLIV
favicon: null
layout_spectrum: 0.14003
typography_spectrum: 0.61217
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1c1c'
    - '#9a9a9a'
    - '#777777'
    - '#dbdbdb'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
