name: Be Passionate
favicon: null
layout_spectrum: 0.35983
typography_spectrum: 0.99575
title: Be Passionate
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#484747'
    - '#a5a4a4'
    - '#e55a21'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
