name: RCGLIV
favicon: null
layout_spectrum: 0.9748617662116885
typography_spectrum: 0.5693751866929233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.30504249106161296
  lightness: 0.12640080554410815
  saturation: 0.5830285565461963
  rhythmicContrast: 0.615816286765039
purpose: []
