name: Be Passionate
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Rafael Cifuentes '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1c1c'
    - '#9a9a9a'
    - '#777777'
    - '#dbdbdb'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
