name: RCGLIV
favicon: null
layout_spectrum: 0.75147
typography_spectrum: 0.75
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d253c'
    - '#af8c6e'
    - '#d9c5b0'
    - '#773e28'
  brandStrength: 0.5
  lightness: 0.12640080554410815
  saturation: 0.5830285565461963
  rhythmicContrast: 0.615816286765039
purpose: []
