favicon: null
name: RCGLIV
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5830285565461963
  brandStrength: 0.5
  rhythmicContrast: 0.615816286765039
  brandColors:
    - '#ffffff'
    - '#1d253c'
    - '#af8c6e'
    - '#d9c5b0'
    - '#773e28'
  lightness: 0.1264008055441082
typography_spectrum: 0.75
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4982079
analytics:
  twitter: null
  google: null
  facebook: null
